// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9RSHruzWiiMRICGn7z-cAxT30xuzur1E',
    appId: '1:550451781539:web:69e1dbc73f3cf98f648416',
    messagingSenderId: '550451781539',
    projectId: 'collar-a9ada',
    authDomain: 'collar-a9ada.firebaseapp.com',
    storageBucket: 'collar-a9ada.appspot.com',
    measurementId: 'G-311S53133G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcG_g18pp_VyyjECTVweCkCB7CWhiAxto',
    appId: '1:550451781539:android:3cdf3b6007ee6425648416',
    messagingSenderId: '550451781539',
    projectId: 'collar-a9ada',
    storageBucket: 'collar-a9ada.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHISR-VMPeocgmzoBVrNtQE2hojyxad9w',
    appId: '1:550451781539:ios:1ed3319fe3d3d3d6648416',
    messagingSenderId: '550451781539',
    projectId: 'collar-a9ada',
    storageBucket: 'collar-a9ada.appspot.com',
    iosBundleId: 'com.example.collar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHISR-VMPeocgmzoBVrNtQE2hojyxad9w',
    appId: '1:550451781539:ios:0eea700bcb41fdd4648416',
    messagingSenderId: '550451781539',
    projectId: 'collar-a9ada',
    storageBucket: 'collar-a9ada.appspot.com',
    iosBundleId: 'com.example.collar.RunnerTests',
  );
}
